from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('customers/', views.CustomerAnalyticsView.as_view(), name='customers'),
    path('rfm/', views.RFMView.as_view(), name='rfm'),
    path('cohorts/', views.CohortView.as_view(), name='cohorts'),
    path('payments/', views.PaymentView.as_view(), name='payments'),
    path('discounts/', views.DiscountView.as_view(), name='discounts'),
    path('staff/', views.StaffView.as_view(), name='staff'),
    path('branches/', views.BranchView.as_view(), name='branches'),
    path('loyalty-gap/', views.LoyaltyGapView.as_view(), name='loyalty_gap'),
    path('retail-analytics/', views.RetailAnalyticsView.as_view(), name='retail_analytics'),
    path('invalid-mobiles/', views.InvalidMobilesView.as_view(), name='invalid_mobiles'),
    path('db-manager/', views.DBManagerView.as_view(), name='db_manager'),
    path('target-executive/', views.TargetExecutiveView.as_view(), name='target_executive'),
    path('react-dashboard/', views.ReactDashboardView.as_view(), name='react_dashboard'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('security/', views.SecurityView.as_view(), name='security'),
    path('forecast/lstm/', views.LstmForecastView.as_view(), name='lstm_forecast'),
    path('forecast/propensity/api/', views.PropensityForecastAPIView.as_view(), name='propensity_forecast_api'),
    path('customer-intelligence/', views.CustomerPropensityView.as_view(), name='customer_propensity'),
    path('api/v1/customer-propensity/search/', views.CustomerPropensitySearchAPIView.as_view(), name='customer_propensity_search'),
    path('api/v1/customer-propensity/rebuild/', views.CustomerPropensityRebuildAPIView.as_view(), name='customer_propensity_rebuild'),
    path('report-generator/', RedirectView.as_view(url='/enterprise-dashboard/', permanent=False)),
    path('enterprise-dashboard/', views.EnterpriseDashboardView.as_view(), name='enterprise_dashboard'),
    path('api/v1/enterprise-dashboard/', views.EnterpriseDashboardAPIView.as_view(), name='enterprise_dashboard_api'),
    path('api/v1/enterprise-dashboard/export/', views.EnterpriseDashboardExportAPIView.as_view(), name='enterprise_dashboard_export'),
    path('monthly-retention/', views.MonthlyRetentionView.as_view(), name='monthly_retention'),
    path('api/v1/monthly-retention/', views.MonthlyRetentionAPIView.as_view(), name='monthly_retention_api'),
    path('campaign-analysis/', views.CampaignAnalysisView.as_view(), name='campaign_analysis'),
    path('api/v1/campaign-analysis/', views.CampaignAnalysisAPIView.as_view(), name='campaign_analysis_api'),
    path('she-start/', views.SheStartView.as_view(), name='she_start'),
    path('api/v1/she-start/data/', views.SheStartDataAPIView.as_view(), name='she_start_data_api'),
    path('api/v1/she-start/save-score/', views.SheStartSaveScoreAPIView.as_view(), name='she_start_save_score_api'),
    path('she-start-detailed/', views.SheStartDetailedView.as_view(), name='she_start_detailed'),
    path('api/v1/she-start-detailed/data/', views.SheStartDetailedDataAPIView.as_view(), name='she_start_detailed_data_api'),
]
