import csv
import io

class ExportService:
    @staticmethod
    def export_to_csv(data: list) -> str:
        """
        Converts a list of dictionaries to a CSV string.
        """
        if not data:
            return ""
            
        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=data[0].keys())
        writer.writeheader()
        writer.writerows(data)
        return output.getvalue()

    @staticmethod
    def export_to_text(markdown_content: str) -> str:
        """
        Processes Markdown content for text/pdf export.
        """
        # In a production environment, this would use WeasyPrint or ReportLab to generate a real PDF.
        # For Phase 11 simulation, we return the formatted text.
        header = "=== myG Enterprise AI Report ===\n\n"
        footer = "\n\n=== Generated by myG AI Agent ==="
        return header + markdown_content + footer
