# Generated by Django 6.0.3 on 2026-06-02 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('matched_agent', models.CharField(max_length=100)),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
