# Generated by Django 6.0.4 on 2026-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_aiauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='is_async',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
