# Generated by Django 6.0.4 on 2026-06-03 10:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_aiauditlog_cache_hit_aiauditlog_is_async_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('columns_json', models.JSONField(default=list)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_schema_vectors',
            },
        ),
    ]
