# Generated by Django 6.0.3 on 2026-06-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_schemavector'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='reasoning_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
