# Generated by Django 6.0.3 on 2026-05-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_seed_forecast_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('product', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('sold_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Product Sales',
                'indexes': [models.Index(fields=['date', 'product'], name='analytics_p_date_095c28_idx')],
            },
        ),
    ]
