# Generated by Django 6.0.3 on 2026-05-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_productsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheStartCandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('interview', models.FloatField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, null=True)),
                ('need', models.FloatField(blank=True, null=True)),
                ('emotional', models.FloatField(blank=True, null=True)),
                ('sustainability', models.FloatField(blank=True, null=True)),
                ('utilization', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'She Start Score Override',
                'verbose_name_plural': 'She Start Score Overrides',
            },
        ),
    ]
