# Generated by Django 6.0.3 on 2026-05-30 03:31

from django.db import migrations


def create_shestart_user(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    if not User.objects.filter(username='shestart').exists():
        User.objects.create_user('shestart', password='shestart123')

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_shestartcandidatescore'),
    ]

    operations = [
        migrations.RunPython(create_shestart_user),
    ]
